name: Docker Imajini Olustur ve Gonder

# Bu robot ne zaman çalışsın?
on:
  push:
    branches: [ "main" ] # Sadece 'main' dalına kod gelince çalış.

jobs:
  build-push:
    runs-on: ubuntu-latest # Robot, sanal bir Ubuntu makinede çalışsın.
    
    steps:
      # 1. Adım: Kodları GitHub'dan çek
      - name: Kodlari Cek (Checkout)
        uses: actions/checkout@v3

      # 2. Adım: Docker Hub'a Giris Yap (Login)
      - name: Docker Hub Giris
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Gizli anahtarı kullan
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Adım: Imajı Pişir ve Gönder (Build & Push)
      - name: Build ve Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # DIKKAT: asagidaki 'kullaniciadi' kismini kendi adinla degistir!
          tags: dgknkrl/otomatik-imaj:latest